### ISSUE TITLE
The description of index html. spelling

### ISSUE THREAD

**Issue by felunaix** [luishmcmoreno/hacktoberfest-hack#14]
Please correct the spelling of index.html description

**Comment by luishmcmoreno** [comment]
Hello, correct where?
What description are you talking about?

Thank you.

**Comment by felunaix** [comment]
The upper commit Right there (apge instead of page):
https://github.com/luishmcmoreno/hacktoberfest-hack/commits/master/index.html?author=mateusduraes

**Comment by mateusduraes** [comment]
It is not necessary
Thank you.
